vim.keymap.set("n", "<leader>sp", vim.cmd.Ex)
vim.keymap.set("n", "<leader>y", '"*yy')
vim.keymap.set("n", "<leader>p", '"*p')
vim.keymap.set("n", "<leader>P", '"*P')
vim.keymap.set("v", "<leader>y", '"*yy')
vim.keymap.set("v", "<leader>d", '"*d')
vim.keymap.set("v", "<leader>p", '"*P')
vim.keymap.set("v", "<leader>P", '"*P')
vim.keymap.set("n", "<M-j>", ":m +1<CR>")
vim.keymap.set("i", "<M-j>", "<Esc>:m +1<CR>gi")
vim.keymap.set("n", "<M-k>", ":m -2<CR>")
vim.keymap.set("i", "<M-k>", "<Esc>:m -2<CR>gi")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("v", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("v", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "<C-f>", "<cmd>silent !tmux neww tmux-sessionizer<CR>")
vim.keymap.set("n", "<CR>", "o<Esc>")
vim.keymap.set("n", "gn", ":bnext<CR>")
vim.keymap.set("n", "gp", ":bprevious<CR>")
vim.keymap.set("n", "gx", ":bdelete<CR>")
