vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<leader>sp", vim.cmd.Ex, { desc = "[S]earch [P]roject Tree" })
vim.keymap.set("n", "<leader>y", '"*yy', { desc = "[Y]ank line to system clipboard" })
vim.keymap.set("n", "<leader>p", '"*p', { desc = "[P]aste line from system clipboard" })
vim.keymap.set("n", "<leader>P", '"*P', { desc = "[P]aste line from system clipboard" })
vim.keymap.set("v", "<leader>y", '"*yy', { desc = "[Y]ank selection to system clipboard" })
vim.keymap.set("v", "<leader>d", '"*d', { desc = "[D]elete selection without yanking" })
vim.keymap.set("v", "<leader>p", '"*P', { desc = "[P]aste selection from system clipboard" })
vim.keymap.set("v", "<leader>P", '"*P', { desc = "[P]aste selection from system clipboard" })
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("v", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("v", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "<CR>", "o<Esc>")
vim.keymap.set("n", "gn", ":bnext<CR>", { desc = "[G]o to [N]ext buffer" })
vim.keymap.set("n", "gp", ":bprevious<CR>", { desc = "[G]o to [P]revious buffer" })
